### ISSUE TITLE
Scrollbar is not there if there are too many colors

### ISSUE THREAD

**Issue by bennymeier** [ailon/markerjs2#173]
Hi,

Im using a lot of colors. In the default it looks like this:
![image](https://github.com/ailon/markerjs2/assets/28210970/35439c29-353f-4689-b319-8dd7a9b60801)
The problem is also the `overflow: hidden` which is set as an inline-style.
```html
<div
  class="__markerjs2__1_toolbox-panel-row __markerjs2__1_toolbox-panel-row_colors __markerjs2__1_fade_in"
  style="display: flex; visibility: visible"
>
  <div style="overflow: hidden; white-space: nowrap; margin: 10px">
    <!-- all the color buttons -->
  </div>
</div>
```
I hope you can remove the inline-style there. Here is how it could be fixed if you add this styles to the div-container:
```css
div {
    overflow-y: hidden;
    overflow-x: scroll;
    white-space: nowrap;
    margin: 10px 10px 0px 10px
}

div::-webkit-scrollbar-thumb {
    background: #000000;
}

div::-webkit-scrollbar {
    height: 8px;
    background: #fff;
}
```

I mean the second div:
```html
<div
  class="__markerjs2__1_toolbox-panel-row __markerjs2__1_toolbox-panel-row_colors __markerjs2__1_fade_in"
  style="display: flex; visibility: visible"
>
  <div
    style="
      overflow-y: hidden;
      overflow-x: scroll;
      white-space: nowrap;
      margin: 10px 10px 0px 10px;
    "
  >
  <!-- all the color buttons -->
  </div>
</div>
```

If you add this to it, it looks like this and is horizontal scrollable:
![image](https://github.com/ailon/markerjs2/assets/28210970/57468d4a-5396-450a-bb57-80db352fc9bb)

I prefer adding a css class to this div-container. It will also works for the `line width`, `line style` and all other settings in the toolbox.

Thanks a lot!
